# alembic/script.py.mako
"""Some changes to db, added blocking users

Revision ID: 262b971a83ed
Revises: b3c4d5e6f7g8
Create Date: 2025-06-26 14:52:22.579532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '262b971a83ed'
down_revision = 'b3c4d5e6f7g8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.drop_constraint('profile_versions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('profile_versions_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('user_profiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('user_profiles_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, default=True, server_default="true"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('user_profiles_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('user_profiles_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.drop_constraint('profile_versions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('profile_versions_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###