# alembic/script.py.mako
"""ArticleFull table added

Revision ID: a9eeee7a42e2
Revises: a1b2c3d4e5f6
Create Date: 2025-06-05 09:58:17.235660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a9eeee7a42e2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_full_text',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'commit_id')
    )
    with op.batch_alter_table('articles_full_text', schema=None) as batch_op:
        batch_op.create_index('ix_articles_full_article_id', ['article_id'], unique=False)
        batch_op.create_index('ix_articles_full_commit_id', ['commit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles_full_text', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_full_commit_id')
        batch_op.drop_index('ix_articles_full_article_id')

    op.drop_table('articles_full_text')
    # ### end Alembic commands ###