# alembic/script.py.mako
"""Many to many

Revision ID: f63005945254
Revises: c8992a2ee793
Create Date: 2025-06-30 11:33:33.002252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f63005945254'
down_revision = 'c8992a2ee793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_article_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('media_commit_id_fkey', type_='foreignkey')
        batch_op.drop_column('article_id')
        batch_op.drop_column('commit_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('media_commit_id_fkey', 'commits', ['commit_id'], ['id'])
        batch_op.create_foreign_key('media_article_id_fkey', 'articles', ['article_id'], ['id'])

    # ### end Alembic commands ###