# alembic/script.py.mako
"""Added another missed column

Revision ID: 32c0025cfdc6
Revises: 0dfc6b14972b
Create Date: 2026-04-28 17:35:53.192199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32c0025cfdc6'
down_revision = '0dfc6b14972b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###