# alembic/script.py.mako
"""Added missing column in moderation

Revision ID: b66b834b1612
Revises: dc5ca7525cd0
Create Date: 2026-04-28 15:23:49.084991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b66b834b1612'
down_revision = 'dc5ca7525cd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['reported_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reported_by_id')

    # ### end Alembic commands ###