# alembic/script.py.mako
"""Support for trigrams and indeces for FTS

Revision ID: d26b1e10eb14
Revises: f63005945254
Create Date: 2026-03-11 18:25:03.460567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd26b1e10eb14'
down_revision = 'f63005945254'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # Индекс для нечёткого поиска по заголовку (триграммы)
    op.create_index(
        'ix_articles_title_trgm',
        'articles',
        ['title'],
        postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'}
    )

    # Индексы для полнотекстового поиска по содержанию (разные конфигурации)
    op.create_index(
        'ix_articles_full_text_tsv_ru',
        'articles_full_text',
        [sa.text("to_tsvector('russian', text)")],
        postgresql_using='gin'
    )

    # Дополнительный индекс для ускорения соединения по commit_id
    op.create_index(
        'ix_articles_full_text_commit_id',
        'articles_full_text',
        ['commit_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_title_trgm')
    op.drop_index('ix_articles_full_text_tsv_ru')
    op.drop_index('ix_articles_full_text_commit_id')
    # ### end Alembic commands ###