# alembic/script.py.mako
"""Added another missed column

Revision ID: e50ea5b3dc15
Revises: b66b834b1612
Create Date: 2026-04-28 16:06:56.633729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e50ea5b3dc15'
down_revision = 'b66b834b1612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###