# alembic/script.py.mako
"""Sync table

Revision ID: dc5ca7525cd0
Revises: 1f2e9e9f54cf
Create Date: 2026-03-13 14:54:39.607041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc5ca7525cd0'
down_revision = '1f2e9e9f54cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_sync_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_sync_queue', schema=None) as batch_op:
        batch_op.create_index('ix_typesense_sync_queue_article_id', ['article_id'], unique=False)
        batch_op.create_index('ix_typesense_sync_queue_created_at', ['created_at'], unique=False)



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_sync_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_typesense_sync_queue_created_at')
        batch_op.drop_index('ix_typesense_sync_queue_article_id')

    op.drop_table('search_sync_queue')
    # ### end Alembic commands ###