# alembic/script.py.mako
"""Added another missed column

Revision ID: 0dfc6b14972b
Revises: 94a942eef080
Create Date: 2026-04-28 17:33:54.442704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dfc6b14972b'
down_revision = '94a942eef080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation', schema=None) as batch_op:
        batch_op.drop_column('reason')
    # ### end Alembic commands ###