# alembic/script.py.mako
"""TSV table update and triggers

Revision ID: 1f2e9e9f54cf
Revises: f63005945254
Create Date: 2026-03-11 20:44:51.793013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1f2e9e9f54cf'
down_revision = 'f63005945254'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_full_text', sa.Column('tsv_ru', postgresql.TSVECTOR))
    op.add_column('articles_full_text', sa.Column('tsv_en', postgresql.TSVECTOR))

    # Создаём GIN индексы на этих колонках
    op.create_index(
        'ix_articles_full_text_tsv_ru_gin',
        'articles_full_text',
        ['tsv_ru'],
        postgresql_using='gin'
    )
    op.create_index(
        'ix_articles_full_text_tsv_en_gin',
        'articles_full_text',
        ['tsv_en'],
        postgresql_using='gin'
    )

    # Заполняем существующие записи
    op.execute("""
        UPDATE articles_full_text
        SET tsv_ru = to_tsvector('russian', text),
            tsv_en = to_tsvector('english', text)
    """)

    # Триггер для автоматического обновления при вставке/изменении
    op.execute("""
        CREATE OR REPLACE FUNCTION update_tsv_columns()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.tsv_ru := to_tsvector('russian', NEW.text);
            NEW.tsv_en := to_tsvector('english', NEW.text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trigger_update_tsv
        BEFORE INSERT OR UPDATE ON articles_full_text
        FOR EACH ROW EXECUTE FUNCTION update_tsv_columns();
    """)

    # Индекс для быстрого получения последнего коммита в main ветке
    op.create_index(
        'ix_branches_article_name_created',
        'branches',
        ['article_id', 'name', sa.text('created_at DESC NULLS LAST')]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_branches_article_name_created')
    op.execute("DROP TRIGGER IF EXISTS trigger_update_tsv ON articles_full_text")
    op.execute("DROP FUNCTION IF EXISTS update_tsv_columns()")
    op.drop_index('ix_articles_full_text_tsv_en_gin')
    op.drop_index('ix_articles_full_text_tsv_ru_gin')
    op.drop_column('articles_full_text', 'tsv_en')
    op.drop_column('articles_full_text', 'tsv_ru')
    # ### end Alembic commands ###