# alembic/script.py.mako
"""More indeces

Revision ID: 7a13af481f86
Revises: d26b1e10eb14
Create Date: 2026-03-11 19:41:45.818660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7a13af481f86'
down_revision = 'd26b1e10eb14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_index(
        'ix_branches_main_latest',
        'branches',
        ['article_id', 'created_at'],
        postgresql_where=sa.text("name = 'main'")
    )
    
    # Индекс для сортировки по рангу (будет использоваться частично)
    # Сам ранг вычисляется на лету, но можно добавить составной индекс на статус и id
    op.create_index(
        'ix_articles_status_id',
        'articles',
        ['status', 'id']
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_branches_main_latest')
    op.drop_index('ix_articles_status_id')

    # ### end Alembic commands ###